const U='https://raw.githubusercontent.com/jmtghbd67p-commits/56wan/b955826059538b3819e44d96efa62b32474e653d/api/app.js',M='/94e0a945245fbdc87caf1c0152cc81f6c8dc0940/api/app.js';let H;
function patch(s){s=String(s||'');return s.replace('queries: ["피자 만들기 체험", "쿠킹 체험", "도예 체험", "어린이 공방 체험", "베이킹 체험", "어린이 미술 체험", "농장 체험", "수확 체험"],','queries: ["플레이랩", "흙놀이", "슬라임카페", "슬라임 체험", "오감놀이", "물감놀이", "창의놀이", "어린이 도예 체험", "어린이 베이킹 체험"],').replace('include: ["공방", "체험", "도예", "도자기", "베이킹", "미술", "공예", "요리"]','include: ["공방", "체험", "도예", "도자기", "베이킹", "미술", "공예", "요리", "키즈카페", "흙놀이", "물감놀이", "오감놀이", "창의놀이", "슬라임", "플레이랩"]').replace('queries: ["어린이 물놀이장", "계곡 물놀이", "어린이 야외수영장", "워터파크"],','queries: ["어린이 물놀이장", "계곡 물놀이", "어린이 야외수영장", "워터파크", "실내 워터파크", "실내 물놀이", "아쿠아나", "아쿠아 워터파크", "온천 워터파크"],').replace('if (definition === THEME.craft) return isChildCraftVenue(doc);','if (definition === THEME.craft) return /플레이랩|흙놀이|모래놀이|물감놀이|오감놀이|미술놀이|창의놀이|촉감놀이|슬라임/.test(text) || isChildCraftVenue(doc);')}
function pf(i,n){const u=typeof i==='string'?i:String(i?.url||i||'');return fetch(i,n).then(async r=>{if(!u.includes(M)||!r.ok)return r;const h=new Headers(r.headers);h.delete('content-length');return new Response(patch(await r.text()),{status:r.status,statusText:r.statusText,headers:h})})}
async function base(){if(!H)H=(async()=>{const r=await fetch(U,{cache:'force-cache'});if(!r.ok)throw Error('기준본 로드 실패 '+r.status);const m={exports:{}};new Function('module','exports','require','process','fetch','URL','URLSearchParams','AbortController','Buffer','console','setTimeout','clearTimeout','Response','Headers',await r.text())(m,m.exports,require,process,pf,URL,URLSearchParams,AbortController,Buffer,console,setTimeout,clearTimeout,Response,Headers);return m.exports})().catch(e=>{H=null;throw e});return H}
function cap(){let b='',c=200,h={};return{get statusCode(){return c},set statusCode(v){c=v},setHeader(k,v){h[k]=v},getHeader(k){return h[k]},write(v=''){b+=v},end(v=''){b+=v},out:()=>({b,c,h})}}
function ymd(v){return /^\d{4}-\d{2}-\d{2}$/.test(v||'')?v:new Date().toISOString().slice(0,10)}function bt(d,a,b){d=ymd(d);return d>=a&&d<=b}
function wt(x){return `${x.name||x.display_name||''} ${x.category||''} ${x.road_address||x.address||''}`}
function water(a,date){const d=ymd(date),strong=/워터파크|물놀이장|물놀이터|수변놀이터|키즈풀|유아풀|워터슬라이드|어린이.*물놀이|유아.*물놀이|키즈.*물놀이|아쿠아나/i,bad=/휘트니스|피트니스|헬스|스포츠센터|수영강습|수영교실|사우나|호텔/i;return(a||[]).filter(x=>{const t=wt(x);if(bad.test(t)&&!strong.test(t))return false;if(!strong.test(t)&&!/계곡.*물놀이|분수.*물놀이|야외수영장/i.test(t))return false;if(/월출산.*기찬랜드/i.test(t))return bt(d,'2026-07-11','2026-08-17');if(/쌍학어린이공원.*물놀이|쌍학.*물놀이장/i.test(t))return bt(d,'2026-07-21','2026-08-15');if(/상무시민공원.*물놀이|마륵(?:근린)?공원.*물놀이/i.test(t))return bt(d,'2026-07-21','2026-08-15');if(/무안청사.*워터스퀘어/i.test(t))return bt(d,'2026-07-24','2026-08-30');if(/기찬랜드/i.test(t)){const m=d.slice(5);return m>='07-15'&&m<='08-31'}if(/야외수영장|바닥분수|분수.*물놀이|계곡.*물놀이|공원.*물놀이장|어린이공원.*물놀이/i.test(t)){const m=d.slice(5);return m>='07-15'&&m<='08-31'}return true}).map(x=>{const t=wt(x),yr=/아쿠아나|아쿠아시티|실내.*(?:워터파크|물놀이|키즈풀|유아풀)|(?:워터파크|물놀이|키즈풀|유아풀).*실내/i.test(t),se=/기찬랜드|쌍학어린이공원.*물놀이|상무시민공원.*물놀이|마륵(?:근린)?공원.*물놀이|무안청사.*워터스퀘어|야외수영장|바닥분수|분수.*물놀이|계곡.*물놀이|공원.*물놀이장|어린이공원.*물놀이/i.test(t);return{...x,matched_themes:['water'],water_operation:yr?'year_round':se?'seasonal':'unknown',...(yr?{water_badge:'상시 운영'}:se?{water_badge:'여름 한정'}:{})}})}
function craft(a){const bad=/치료|상담|심리|발달|병원|의원|어린이집|유치원|학원|교습|교육원|성인전용|전문디자인|플레이랩미디어|디자인업|광고|기업|화방|갤러리|미술관/i,direct=/흙놀이|모래놀이|물감놀이|오감놀이|미술놀이|창의놀이|촉감놀이|슬라임|타카플레이카페|플레이랩\s*(광주|키즈|화정|첨단|수완|상무|봉선|점)/i,child=/(어린이|유아|키즈|아동).*(공방|공예|도예|도자기|베이킹|쿠킹|요리|미술|목공|체험)|(공방|공예|도예|도자기|베이킹|쿠킹|요리|미술|목공|체험).*(어린이|유아|키즈|아동)/i,hands=/공방|공예|도예|도자기|베이킹|쿠킹|요리|미술|목공|슬라임|체험/i;return(a||[]).filter(x=>{const t=`${x.name||''} ${x.category||''}`;return !x.route_estimated&&!bad.test(t)&&(direct.test(t)||child.test(t)||hands.test(t)&&/공방|도예|도자기|베이킹|쿠킹|요리|목공/i.test(t))})}
function exp(a){return(a||[]).filter(x=>x.official_child_program_evidence===true||(+x.family_evidence||0)>=2||/어린이|유아|키즈|과학관|체험관/i.test(`${x.name||''} ${x.category||''}`))}
function playground(a){return(a||[]).filter(x=>{const t=`${x.name||''} ${x.category||''}`;if(/유아학습|놀이교육|교육,학문|영,유아,아동|학원|교습|키즈카페|실내놀이터|트램폴린|스포츠|휘트니스|주차장/i.test(t))return false;return /놀이터|어린이공원|유아숲|놀이시설|모래놀이/i.test(t)})}
function dedupe(a){const m=new Map;for(const x of a||[]){const k=x.id||`${x.x}:${x.y}:${x.name}`;if(!m.has(k))m.set(k,x);else{const o=m.get(k);m.set(k,{...o,matched_themes:[...new Set([...(o.matched_themes||[]),...(x.matched_themes||[])])]})}}return[...m.values()]}
function naverHeaders(){return{'X-NCP-APIGW-API-KEY-ID':process.env.NAVER_API_KEY_ID||'','X-NCP-APIGW-API-KEY':process.env.NAVER_API_KEY_SECRET||''}}
function clean(s){return String(s||'').replace(/<[^>]+>/g,'').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim()}
function locOf(x){let a=String(x.road_address||x.address||'').trim();a=a.replace(/전남광주통합특별시/g,'광주').replace(/서울특별시/g,'서울').replace(/부산광역시/g,'부산').replace(/대구광역시/g,'대구').replace(/인천광역시/g,'인천').replace(/광주광역시/g,'광주').replace(/대전광역시/g,'대전').replace(/울산광역시/g,'울산').replace(/세종특별자치시/g,'세종').replace(/경기도/g,'경기').replace(/강원특별자치도|강원도/g,'강원').replace(/충청북도/g,'충북').replace(/충청남도/g,'충남').replace(/전북특별자치도|전라북도/g,'전북').replace(/전라남도/g,'전남').replace(/경상북도/g,'경북').replace(/경상남도/g,'경남').replace(/제주특별자치도|제주도/g,'제주');const p=a.split(/\s+/).filter(Boolean);return p.slice(0,2).join(' ')}
async function nblog(q,display=100){if(!process.env.NAVER_API_KEY_ID||!process.env.NAVER_API_KEY_SECRET)return[];try{const r=await fetch('https://naverapihub.apigw.ntruss.com/search/v1/blog?display='+display+'&sort=date&query='+encodeURIComponent(q),{headers:naverHeaders()});if(!r.ok)return[];return (await r.json()).items||[]}catch{return[]}}
function dateNumDaysAgo(days){const d=new Date();d.setDate(d.getDate()-days);return +`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
async function blog7(x){const name=clean(x.name||x.display_name);if(!name)return 0;const items=await nblog(`${name} ${locOf(x)}`,100),min=dateNumDaysAgo(7),key=name.replace(/\s+/g,'').toLowerCase(),seen=new Set;for(const b of items){if(+(b.postdate||0)<min)continue;const text=clean(`${b.title||''} ${b.description||''}`).replace(/\s+/g,'').toLowerCase();if(!text.includes(key))continue;seen.add(b.link||b.bloggerlink||`${b.bloggername}:${b.postdate}:${b.title}`)}return seen.size}
function isArtMuseum(x){return /미술관/i.test(`${x.name||''} ${x.category||''}`)}
function isPublicOrMajorMuseum(x){const t=`${x.name||''} ${x.category||''} ${x.place_url||''}`;return /국립|시립|도립|구립|군립|공립|광역시.*미술관|특별시.*미술관|리움|호암미술관|아모레퍼시픽미술관|뮤지엄\s*산|부산현대미술관|서울시립미술관|광주시립미술관|대구미술관|대전시립미술관|전남도립미술관|경남도립미술관|제주도립미술관/i.test(t)}
async function childReview365(x){const name=clean(x.name||x.display_name);if(!name)return 0;const terms=['아이','아기','어린이','유아','가족'];const min=dateNumDaysAgo(365),key=name.replace(/\s+/g,'').toLowerCase(),seen=new Set;for(const term of terms){const items=await nblog(`${name} ${locOf(x)} ${term}`,30);for(const b of items){if(+(b.postdate||0)<min)continue;const text=clean(`${b.title||''} ${b.description||''}`).replace(/\s+/g,'').toLowerCase();if(!text.includes(key)||!/아이와|아이랑|아이와함께|아기랑|아기와|어린이|유아|가족|자녀|아이들/.test(text))continue;seen.add(b.link||b.bloggerlink||`${b.bloggername}:${b.postdate}:${b.title}`)}}return seen.size}
async function museumGate(a){const out=[];for(const x of a||[]){if(!isArtMuseum(x)||isPublicOrMajorMuseum(x)){out.push(x);continue}const n=await childReview365(x);if(n>0)out.push({...x,child_blog_365d_count:n});}return out}
async function rankBlogs(a){const rows=await Promise.all((a||[]).map(async(x,i)=>({...x,blog_7d_count:await blog7(x),_i:i})));rows.sort((a,b)=>(b.blog_7d_count-a.blog_7d_count)||((+a.route_minutes||9999)-(+b.route_minutes||9999))||(a._i-b._i));return rows.map(({_i,...x})=>x)}
async function call(req,u,t){const v=new URL(u.toString());v.searchParams.set('themes',t==='water'?'season':t);const c=cap();await(await base())({...req,url:v.pathname+'?'+v.searchParams.toString(),query:{...(req.query||{}),themes:v.searchParams.get('themes')}},c);const o=c.out();let j;try{j=JSON.parse(o.b||'{}')}catch{return{j:null,o}}return{j,o}}

const KAKAO_KEY=process.env.KAKAO_REST_KEY||'';
const KOPIS_KEY=process.env.KOPIS_API_KEY||'';
const KOPIS_BASE='http://www.kopis.or.kr/openApi/restful';
function sendJson(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
function koreaYmd(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=t=>p.find(x=>x.type===t)?.value||'';return `${get('year')}${get('month')}${get('day')}`}
async function counterValue(name){try{const r=await fetch(`https://counterapi.com/api/56wan.vercel.app/view/${name}`,{cache:'no-store'}),t=await r.text();let j={};try{j=JSON.parse(t)}catch{};const n=Number(j?.count??j?.value??j?.data?.count??j?.data?.value);return Number.isFinite(n)?Math.max(0,Math.floor(n)):0}catch{return 0}}
async function visitCounter(){const[count,today]=await Promise.all([counterValue('home'),counterValue(`home-${koreaYmd()}`)]);return{count,today}}
function stripXml(v=''){return String(v).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim()}
function xf(xml,tag){const m=String(xml||'').match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?stripXml(m[1]):''}
function xdbs(xml){return [...String(xml||'').matchAll(/<db>([\s\S]*?)<\/db>/gi)].map(m=>m[1])}
function kpDate(s){const m=String(s||'').match(/(\d{4})[.\/-]?(\d{1,2})[.\/-]?(\d{1,2})/);return m?`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`:''}
function minusDays(iso,n){const d=new Date(`${iso}T12:00:00+09:00`);d.setDate(d.getDate()-n);return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
function kp8(iso){return String(iso||'').replace(/-/g,'')}
async function kakaoJson(url){if(!KAKAO_KEY)return{};const r=await fetch(url,{headers:{Authorization:`KakaoAK ${KAKAO_KEY}`},cache:'no-store'});return r.json().catch(()=>({}))}
async function regionAt(x,y){const j=await kakaoJson(`https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?${new URLSearchParams({x:String(x),y:String(y)})}`);return (j.documents||[]).find(v=>v.region_type==='H')||j.documents?.[0]||null}
function kopisCodes(region){const p=String(region?.region_1depth_name||'');if(/전남광주통합|광주|전남/.test(p))return ['12','29','46'];const map=[[/서울/,'11'],[/부산/,'26'],[/대구/,'27'],[/인천/,'28'],[/대전/,'30'],[/울산/,'31'],[/세종/,'36'],[/경기/,'41'],[/강원/,'51'],[/충북/,'43'],[/충남/,'44'],[/전북/,'52'],[/경북/,'47'],[/경남/,'48'],[/제주/,'50']];return [map.find(([r])=>r.test(p))?.[1]].filter(Boolean)}
async function kopisList(code,date,kid){if(!KOPIS_KEY)return[];const q=new URLSearchParams({service:KOPIS_KEY,stdate:minusDays(date,30),eddate:kp8(date),cpage:'1',rows:'100',kidstate:kid});if(code)q.set('signgucode',code);const r=await fetch(`${KOPIS_BASE}/pblprfr?${q}`,{cache:'no-store'});const xml=await r.text();if(!r.ok)return[];return xdbs(xml).map(db=>({id:xf(db,'mt20id'),name:xf(db,'prfnm'),from:kpDate(xf(db,'prfpdfrom')),to:kpDate(xf(db,'prfpdto')),venue:xf(db,'fcltynm'),genre:xf(db,'genrenm'),area:xf(db,'area'),state:xf(db,'prfstate')})).filter(x=>x.id)}
async function kopisDetail(id){if(!KOPIS_KEY||!id)return null;const r=await fetch(`${KOPIS_BASE}/pblprfr/${encodeURIComponent(id)}?service=${encodeURIComponent(KOPIS_KEY)}`,{cache:'no-store'});const xml=await r.text();const db=xdbs(xml)[0];if(!r.ok||!db)return null;return{id, name:xf(db,'prfnm'),from:kpDate(xf(db,'prfpdfrom')),to:kpDate(xf(db,'prfpdto')),venue:xf(db,'fcltynm'),genre:xf(db,'genrenm'),area:xf(db,'area'),age:xf(db,'prfage'),times:xf(db,'dtguidance'),runtime:xf(db,'prfruntime'),price:xf(db,'pcseguidance'),poster:xf(db,'poster'),state:xf(db,'prfstate')}}
function childAgeOK(age,name=''){const a=String(age||'').replace(/\s+/g,' '),n=String(name||'');if(/영화/i.test(n))return false;if(/전체\s*관람|전\s*연령|누구나/i.test(a))return true;if(/중학생|고등학생|청소년|성인|만\s*1[2-9]\s*세|1[2-9]\s*세\s*이상/i.test(a))return false;if(/\d+\s*개월/i.test(a))return true;const m=a.match(/(?:만\s*)?(\d{1,2})\s*세/);if(m)return Number(m[1])<=11;if(/어린이|아동|유아|초등/i.test(a))return true;return false}
function dayOK(times,date){const t=String(times||'');if(!t)return true;const days=['일','월','화','수','목','금','토'],d=new Date(`${date}T12:00:00+09:00`),want=days[d.getDay()];const found=[...t.matchAll(/([일월화수목금토])요일/g)].map(m=>m[1]);return !found.length||found.includes(want)}
async function kakaoKeyword(q,x,y){const sp=new URLSearchParams({query:q,size:'15',sort:'distance'});if(Number.isFinite(x)&&Number.isFinite(y)){sp.set('x',String(x));sp.set('y',String(y))}const j=await kakaoJson(`https://dapi.kakao.com/v2/local/search/keyword.json?${sp}`);return j.documents||[]}
async function kakaoRoute(origin,target){if(!KAKAO_KEY)return null;const sp=new URLSearchParams({origin:`${origin.x},${origin.y}`,destination:`${target.x},${target.y}`,priority:'TIME',alternatives:'false',road_details:'false'});const r=await fetch(`https://apis-navi.kakaomobility.com/v1/directions?${sp}`,{headers:{Authorization:`KakaoAK ${KAKAO_KEY}`},cache:'no-store'});const j=await r.json().catch(()=>({}));const s=j.routes?.[0]?.summary;if(!s||!Number.isFinite(Number(s.duration)))return null;return{minutes:Math.max(1,Math.round(Number(s.duration)/60)),distance:Number(s.distance)||0}}
async function venuePoint(name,area,x,y){for(const q of [`${name} ${area||''}`.trim(),name]){const docs=await kakaoKeyword(q,x,y);if(docs.length){const d=docs[0];return{id:d.id||'',name:d.place_name||name,category:d.category_name||'',address:d.address_name||'',road_address:d.road_address_name||'',phone:d.phone||'',place_url:d.place_url||'',x:Number(d.x),y:Number(d.y)}}}return null}
async function performanceItems(origin,maxMinutes,date){date=ymd(date);const region=await regionAt(origin.x,origin.y),codes=kopisCodes(region),raw=[];for(const c of codes){for(const kid of ['Y','N']){try{raw.push(...await kopisList(c,date,kid))}catch{}}}const seen=new Set,active=[];for(const x of raw){if(seen.has(x.id))continue;seen.add(x.id);if(x.from&&x.to&&x.from<=date&&date<=x.to&&!/영화/i.test(x.name))active.push(x)}const det=[];for(let i=0;i<active.length;i+=8){const batch=await Promise.all(active.slice(i,i+8).map(x=>kopisDetail(x.id).catch(()=>null)));det.push(...batch.filter(Boolean))}const eligible=det.filter(d=>d.from<=date&&date<=d.to&&childAgeOK(d.age,d.name)&&dayOK(d.times,date)&&!/영화/i.test(`${d.name} ${d.genre}`));const routed=[];for(let i=0;i<eligible.length;i+=6){const batch=await Promise.all(eligible.slice(i,i+6).map(async d=>{const p=await venuePoint(d.venue,d.area,origin.x,origin.y);if(!p)return null;const rt=await kakaoRoute(origin,p);if(!rt||rt.minutes>maxMinutes)return null;return{id:`kopis:${d.id}`,name:d.name,display_name:d.name,category:d.genre||'공연',address:p.address,road_address:p.road_address,phone:p.phone,place_url:p.place_url,x:p.x,y:p.y,matched_themes:['performance'],route_minutes:rt.minutes,route_distance:rt.distance,route_estimated:false,performance:true,performance_age:d.age,performance_times:d.times,performance_venue:d.venue,performance_runtime:d.runtime,performance_price:d.price,poster:d.poster,family_evidence:20}}));routed.push(...batch.filter(Boolean))}return routed.sort((a,b)=>a.route_minutes-b.route_minutes).slice(0,10)}
function animalStrong(t){return /실내동물원|동물원|아쿠아리움|수족관|동물\s*체험|곤충\s*체험|목장\s*체험|체험농장|생태농장|생태농원|생태나라|관광농원|농촌체험|수목원|식물원|함평바나나생태나라/i.test(t)}
function animalAllowed(x){const label=`${x.name||''} ${x.category||''}`,all=`${label} ${x.road_address||x.address||''}`;if(/고양이카페|동물카페|앵무새카페|미어캣카페|라쿤카페|파충류카페|주차장|게이트볼|운동장|체육관|골프|휘트니스|헬스|반려견놀이터|애견놀이터|펫놀이터|주말농장|묘목|나무판매|개장예정|조성중|공사중|20\d{2}년.*예정|음식점|카페|주점|숙박|쇼핑/i.test(label))return false;if(/유아숲|숲체험원|자연휴양림/i.test(all)&&!animalStrong(label))return false;if(/축산업|농업|과일,채소재배|작물재배/i.test(label)&&!animalStrong(x.name||''))return false;return animalStrong(label)}
function addrKey(x){return String(x.road_address||x.address||'').replace(/전남광주통합특별시/g,'').replace(/\s+/g,' ').replace(/\s+(\d+층|\d+호).*$/,'').trim().toLowerCase()}
function animalDedupe(a){const out=[],m=new Map;for(const x of a||[]){const name=String(x.name||x.display_name||'').replace(/\s+/g,'').toLowerCase(),k=`name:${name||addrKey(x)||String(x.id||'')}`;if(!m.has(k)){m.set(k,out.length);out.push(x);continue}const i=m.get(k),o=out[i];const score=z=>(/체험|생태|동물원|수목원|관광농원|함평바나나생태나라/i.test(z.name||'')?5:0)+(+z.family_evidence||0);if(score(x)>score(o))out[i]=x}return out}
async function animalRescue(origin,maxMinutes){const qs=['실내동물원','동물 체험','동물원','아쿠아리움','수목원','생태공원','목장 체험','곤충 체험','고양이카페','앵무새카페','동물카페','미어캣카페','라쿤카페','파충류카페','체험농장','생태농장','생태농원','생태나라','관광농원','농촌체험','바나나','함평바나나생태나라'];let raw=[];for(let i=0;i<qs.length;i+=6){const b=await Promise.all(qs.slice(i,i+6).map(q=>kakaoKeyword(q,origin.x,origin.y).catch(()=>[])));raw.push(...b.flat())}const curated={id:'1154919545',name:'함평바나나생태나라',display_name:'함평바나나생태나라',category:'가족형 생태체험',address:'전남광주통합특별시 함평군 함평읍 대덕리 1128-1',road_address:'전남광주통합특별시 함평군 함평읍 대천길 16-20',phone:'010-7554-6456',place_url:'http://place.map.kakao.com/1154919545',x:126.50196807592144,y:35.07210552018521,matched_themes:['animals'],family_evidence:20,animal_type:'가족형 생태체험'};raw.push({id:curated.id,place_name:curated.name,category_name:curated.category,address_name:curated.address,road_address_name:curated.road_address,phone:curated.phone,place_url:curated.place_url,x:String(curated.x),y:String(curated.y)});const seen=new Set,rows=[];for(const d of raw){if(seen.has(d.id))continue;seen.add(d.id);const x={id:d.id||`${d.x}:${d.y}:${d.place_name}`,name:d.place_name||'',display_name:d.place_name||'',category:d.category_name||'',address:d.address_name||'',road_address:d.road_address_name||'',phone:d.phone||'',place_url:d.place_url||'',x:Number(d.x),y:Number(d.y),matched_themes:['animals'],family_evidence:10};if(animalAllowed(x))rows.push(x)}const routed=[];for(let i=0;i<rows.length;i+=8){const b=await Promise.all(rows.slice(i,i+8).map(async x=>{const rt=await kakaoRoute(origin,x);if(!rt||rt.minutes>maxMinutes)return null;return{...x,route_minutes:rt.minutes,route_distance:rt.distance,route_estimated:false,...(/함평바나나생태나라/i.test(x.name)?{family_evidence:20,animal_type:'가족형 생태체험'}:{})}}));routed.push(...b.filter(Boolean))}return animalDedupe(routed).sort((a,b)=>a.route_minutes-b.route_minutes)}
async function craftRescue(origin,maxMinutes){const qs=['어린이 공방 체험','어린이 도예 체험','키즈 베이킹 체험','어린이 쿠킹 체험','키즈 목공 체험','어린이 미술 체험','도예 공방'];const raw=(await Promise.all(qs.map(q=>kakaoKeyword(q,origin.x,origin.y).catch(()=>[])))).flat(),seen=new Set,rows=[];for(const d of raw){const id=d.id||`${d.x}:${d.y}:${d.place_name}`;if(seen.has(id))continue;seen.add(id);const x={id,name:d.place_name||'',display_name:d.place_name||'',category:d.category_name||'',address:d.address_name||'',road_address:d.road_address_name||'',phone:d.phone||'',place_url:d.place_url||'',x:Number(d.x),y:Number(d.y),matched_themes:['craft']};if(craft([x]).length)rows.push(x)}const routed=[];for(let i=0;i<Math.min(rows.length,36);i+=8){const b=await Promise.all(rows.slice(i,i+8).map(async x=>{const rt=await kakaoRoute(origin,x);return rt&&rt.minutes<=maxMinutes?{...x,route_minutes:rt.minutes,route_distance:rt.distance,route_estimated:false}:null}));routed.push(...b.filter(Boolean))}return dedupe(routed).sort((a,b)=>a.route_minutes-b.route_minutes)}
async function callTheme(req,u,t){if(t==='performance'){const origin={x:Number(u.searchParams.get('x')),y:Number(u.searchParams.get('y'))},max=Math.max(10,Math.min(120,Number(u.searchParams.get('maxMinutes'))||40)),date=u.searchParams.get('visitDate')||ymd('');const items=await performanceItems(origin,max,date);return{j:{ok:true,items,hasMore:false,hasMoreRecommendations:false,transitEnabled:false},o:{c:200,b:''}}}const r=await call(req,u,t),origin={x:Number(u.searchParams.get('x')),y:Number(u.searchParams.get('y'))},max=Math.max(10,Math.min(120,Number(u.searchParams.get('maxMinutes'))||40));if(t==='animals'&&r.j?.ok){const rescue=await animalRescue(origin,max);r.j.items=animalDedupe([...(r.j.items||[]).filter(animalAllowed),...rescue]).sort((a,b)=>(+a.route_minutes||999)-(+b.route_minutes||999)).slice(0,10);r.j.hasMore=(r.j.items||[]).length>=10}if(t==='craft'&&r.j?.ok){const rescue=await craftRescue(origin,max);r.j.items=dedupe([...(r.j.items||[]).filter(x=>craft([x]).length),...rescue]).sort((a,b)=>(+a.route_minutes||999)-(+b.route_minutes||999)).slice(0,12);r.j.hasMore=(r.j.items||[]).length>=10}return r}
function placeId(item){return item&&(item.id||String(item.x)+':'+String(item.y)+':'+String(item.name))}
function themeQuotaItems(groups,total=10){
  const n=groups.length;if(!n)return[];
  const base=Math.floor(total/n),extra=total%n;
  const quota=groups.map((_,i)=>base+(i<extra?1:0));
  const positions=groups.map(()=>0),picked=groups.map(()=>0),out=[],seen=new Set;
  const allThemes=new Map;
  for(const group of groups)for(const item of group.items||[]){const id=placeId(item);if(!id)continue;const set=allThemes.get(id)||new Set;for(const key of item.matched_themes||[])set.add(key);allThemes.set(id,set)}
  const take=i=>{const list=groups[i].items||[];while(positions[i]<list.length){const item=list[positions[i]++],id=placeId(item);if(!item||seen.has(id))continue;seen.add(id);out.push({...item,matched_themes:[...allThemes.get(id)]});picked[i]++;return true}return false};
  // 각 테마의 상위 후보를 먼저 확보한다. 예: 2개 선택=5개씩, 5개 선택=2개씩.
  for(let round=0;round<Math.max(...quota);round++)for(let i=0;i<n;i++)if(picked[i]<quota[i])take(i);
  // 한 테마의 후보가 부족하거나 중복된 경우에만 남는 자리를 다음 순위 후보로 채운다.
  while(out.length<total){let added=false;for(let i=0;i<n&&out.length<total;i++)if(take(i))added=true;if(!added)break}
  return out;
}
module.exports=async(req,res)=>{
  try{
    const u=new URL(req.url,'http://x');
    const mode=u.searchParams.get('mode')||req.query?.mode||'';
    if(mode==='visit')return sendJson(res,200,{ok:true,...await visitCounter()});
    if(mode==='health')return sendJson(res,200,{ok:true,kakao:!!KAKAO_KEY,kopis:!!KOPIS_KEY});
    const ts=(u.searchParams.get('themes')||u.searchParams.get('theme')||'').split(',').filter(Boolean);
    if(!ts.length)return(await base())(req,res);
    const rs=await Promise.all(ts.map(t=>callTheme(req,u,t)));
    const bad=rs.find(r=>!r.j||!r.j.ok);
    if(bad){res.statusCode=bad?.o?.c||500;return res.end(bad?.o?.b||JSON.stringify({ok:false,error:'추천 정보를 불러오지 못했습니다.'}))}
    const groups=[];
    for(let i=0;i<rs.length;i++){
      const t=ts[i];let a=rs[i].j.items||[];
      if(t==='water')a=water(a,u.searchParams.get('visitDate'));
      else if(t==='season')a=a.filter(x=>x.festival||x.season_kind==='festival');
      else if(t==='craft')a=craft(a);
      else if(t==='experience')a=await museumGate(exp(a));
      else if(t==='playground')a=playground(a);
      else if(t==='animals')a=a.filter(animalAllowed);
      a=dedupe(a.map(x=>({...x,matched_themes:[...new Set([...(x.matched_themes||[]).filter(k=>k!=='season'||t==='season'),t])]})));
      // 후기 많은 곳 우선, 같은 후기 수면 가까운 곳 우선은 테마 안에서만 적용한다.
      if(t==='performance')a.sort((x,y)=>(+x.route_minutes||999)-(+y.route_minutes||999));
      else a=await rankBlogs(a);
      groups.push({theme:t,items:a});
    }
    // 가족 적합성 점수는 후보 선별·정렬에만 사용한다. 화면에는 근거가 불명확한 안내 태그를 노출하지 않는다.
    const items=themeQuotaItems(groups,10).map(({family_evidence,official_child_program_evidence,...item})=>item);
    return sendJson(res,200,{ok:true,transitEnabled:false,items,hasMore:rs.some(r=>r.j.hasMore),hasMoreRecommendations:rs.some(r=>r.j.hasMoreRecommendations)});
  }catch(e){
    console.error(e);
    return sendJson(res,500,{ok:false,error:e.message||String(e)});
  }
};
