const U='https://raw.githubusercontent.com/jmtghbd67p-commits/56wan/b955826059538b3819e44d96efa62b32474e653d/api/app.js',M='/94e0a945245fbdc87caf1c0152cc81f6c8dc0940/api/app.js';let H;
function patch(s){s=String(s||'');return s.replace('queries: ["피자 만들기 체험", "쿠킹 체험", "도예 체험", "어린이 공방 체험", "베이킹 체험", "어린이 미술 체험", "농장 체험", "수확 체험"],','queries: ["플레이랩", "흙놀이", "슬라임카페", "슬라임 체험", "오감놀이", "물감놀이", "창의놀이", "어린이 도예 체험", "어린이 베이킹 체험"],').replace('include: ["공방", "체험", "도예", "도자기", "베이킹", "미술", "공예", "요리"]','include: ["공방", "체험", "도예", "도자기", "베이킹", "미술", "공예", "요리", "키즈카페", "흙놀이", "물감놀이", "오감놀이", "창의놀이", "슬라임", "플레이랩"]').replace('queries: ["어린이 물놀이장", "계곡 물놀이", "어린이 야외수영장", "워터파크"],','queries: ["어린이 물놀이장", "계곡 물놀이", "어린이 야외수영장", "워터파크", "실내 워터파크", "실내 물놀이", "아쿠아나", "아쿠아 워터파크", "온천 워터파크"],').replace('if (definition === THEME.craft) return isChildCraftVenue(doc);','if (definition === THEME.craft) return /플레이랩|흙놀이|모래놀이|물감놀이|오감놀이|미술놀이|창의놀이|촉감놀이|슬라임/.test(text) || isChildCraftVenue(doc);')}
function pf(i,n){const u=typeof i==='string'?i:String(i?.url||i||'');return fetch(i,n).then(async r=>{if(!u.includes(M)||!r.ok)return r;const h=new Headers(r.headers);h.delete('content-length');return new Response(patch(await r.text()),{status:r.status,statusText:r.statusText,headers:h})})}
async function base(){if(!H)H=(async()=>{const r=await fetch(U,{cache:'force-cache'});if(!r.ok)throw Error('기준본 로드 실패 '+r.status);const m={exports:{}};new Function('module','exports','require','process','fetch','URL','URLSearchParams','AbortController','Buffer','console','setTimeout','clearTimeout','Response','Headers',await r.text())(m,m.exports,require,process,pf,URL,URLSearchParams,AbortController,Buffer,console,setTimeout,clearTimeout,Response,Headers);return m.exports})().catch(e=>{H=null;throw e});return H}
function cap(){let b='',c=200,h={};return{get statusCode(){return c},set statusCode(v){c=v},setHeader(k,v){h[k]=v},getHeader(k){return h[k]},write(v=''){b+=v},end(v=''){b+=v},out:()=>({b,c,h})}}
function ymd(v){return /^\d{4}-\d{2}-\d{2}$/.test(v||'')?v:new Date().toISOString().slice(0,10)}function bt(d,a,b){d=ymd(d);return d>=a&&d<=b}
function wt(x){return `${x.name||x.display_name||''} ${x.category||''} ${x.road_address||x.address||''}`}
function water(a,date){const d=ymd(date),strong=/워터파크|물놀이장|물놀이터|수변놀이터|키즈풀|유아풀|워터슬라이드|어린이.*물놀이|유아.*물놀이|키즈.*물놀이|아쿠아나/i,bad=/휘트니스|피트니스|헬스|스포츠센터|수영강습|수영교실|사우나|호텔/i;return(a||[]).filter(x=>{const t=wt(x);if(bad.test(t)&&!strong.test(t))return false;if(!strong.test(t)&&!/계곡.*물놀이|분수.*물놀이|야외수영장/i.test(t))return false;if(/월출산.*기찬랜드/i.test(t))return bt(d,'2026-07-11','2026-08-17');if(/쌍학어린이공원.*물놀이|쌍학.*물놀이장/i.test(t))return bt(d,'2026-07-21','2026-08-15');if(/상무시민공원.*물놀이|마륵(?:근린)?공원.*물놀이/i.test(t))return bt(d,'2026-07-21','2026-08-15');if(/무안청사.*워터스퀘어/i.test(t))return bt(d,'2026-07-24','2026-08-30');if(/기찬랜드/i.test(t)){const m=d.slice(5);return m>='07-15'&&m<='08-31'}if(/야외수영장|바닥분수|분수.*물놀이|계곡.*물놀이|공원.*물놀이장|어린이공원.*물놀이/i.test(t)){const m=d.slice(5);return m>='07-15'&&m<='08-31'}return true}).map(x=>{const t=wt(x),yr=/아쿠아나|아쿠아시티|실내.*(?:워터파크|물놀이|키즈풀|유아풀)|(?:워터파크|물놀이|키즈풀|유아풀).*실내/i.test(t),se=/기찬랜드|쌍학어린이공원.*물놀이|상무시민공원.*물놀이|마륵(?:근린)?공원.*물놀이|무안청사.*워터스퀘어|야외수영장|바닥분수|분수.*물놀이|계곡.*물놀이|공원.*물놀이장|어린이공원.*물놀이/i.test(t);return{...x,matched_themes:['water'],water_operation:yr?'year_round':se?'seasonal':'unknown',...(yr?{water_badge:'상시 운영'}:se?{water_badge:'여름 한정'}:{})}})}
function craft(a){const bad=/치료|상담|심리|발달|병원|의원|어린이집|유치원|학원|교습|교육원|성인|가죽|라탄|퀼트|뜨개|플라워|전문디자인|플레이랩미디어|디자인업|광고|기업/i,direct=/흙놀이|모래놀이|물감놀이|오감놀이|미술놀이|창의놀이|촉감놀이|슬라임|타카플레이카페|플레이랩\s*(광주|키즈|화정|첨단|수완|상무|봉선|점)/i,child=/(어린이|유아|키즈|아동).*(공방|공예|도예|베이킹|쿠킹|요리|미술|체험)|(공방|공예|도예|베이킹|쿠킹|요리|미술|체험).*(어린이|유아|키즈|아동)/i;return(a||[]).filter(x=>{const t=`${x.name||''} ${x.category||''}`;return !x.route_estimated&&!bad.test(t)&&(direct.test(t)||child.test(t))})}
function exp(a){return(a||[]).filter(x=>x.official_child_program_evidence===true||(+x.family_evidence||0)>=2||/어린이|유아|키즈|과학관|체험관/i.test(`${x.name||''} ${x.category||''}`))}
function playground(a){return(a||[]).filter(x=>{const t=`${x.name||''} ${x.category||''}`;if(/유아학습|놀이교육|교육,학문|영,유아,아동|학원|교습|키즈카페|실내놀이터|트램폴린|스포츠|휘트니스/i.test(t))return false;return /놀이터|어린이공원|유아숲|놀이시설|모래놀이/i.test(t)})}
function dedupe(a){const m=new Map;for(const x of a||[]){const k=x.id||`${x.x}:${x.y}:${x.name}`;if(!m.has(k))m.set(k,x);else{const o=m.get(k);m.set(k,{...o,matched_themes:[...new Set([...(o.matched_themes||[]),...(x.matched_themes||[])])]})}}return[...m.values()]}
function naverHeaders(){return{'X-NCP-APIGW-API-KEY-ID':process.env.NAVER_API_KEY_ID||'','X-NCP-APIGW-API-KEY':process.env.NAVER_API_KEY_SECRET||''}}
function clean(s){return String(s||'').replace(/<[^>]+>/g,'').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim()}
function locOf(x){let a=String(x.road_address||x.address||'').trim();a=a.replace(/전남광주통합특별시/g,'광주').replace(/서울특별시/g,'서울').replace(/부산광역시/g,'부산').replace(/대구광역시/g,'대구').replace(/인천광역시/g,'인천').replace(/광주광역시/g,'광주').replace(/대전광역시/g,'대전').replace(/울산광역시/g,'울산').replace(/세종특별자치시/g,'세종').replace(/경기도/g,'경기').replace(/강원특별자치도|강원도/g,'강원').replace(/충청북도/g,'충북').replace(/충청남도/g,'충남').replace(/전북특별자치도|전라북도/g,'전북').replace(/전라남도/g,'전남').replace(/경상북도/g,'경북').replace(/경상남도/g,'경남').replace(/제주특별자치도|제주도/g,'제주');const p=a.split(/\s+/).filter(Boolean);return p.slice(0,2).join(' ')}
async function nblog(q,display=100){if(!process.env.NAVER_API_KEY_ID||!process.env.NAVER_API_KEY_SECRET)return[];try{const r=await fetch('https://naverapihub.apigw.ntruss.com/search/v1/blog?display='+display+'&sort=date&query='+encodeURIComponent(q),{headers:naverHeaders()});if(!r.ok)return[];return (await r.json()).items||[]}catch{return[]}}
function dateNumDaysAgo(days){const d=new Date();d.setDate(d.getDate()-days);return +`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
async function blog7(x){const name=clean(x.name||x.display_name);if(!name)return 0;const items=await nblog(`${name} ${locOf(x)}`,100),min=dateNumDaysAgo(7),key=name.replace(/\s+/g,'').toLowerCase(),seen=new Set;for(const b of items){if(+(b.postdate||0)<min)continue;const text=clean(`${b.title||''} ${b.description||''}`).replace(/\s+/g,'').toLowerCase();if(!text.includes(key))continue;seen.add(b.link||b.bloggerlink||`${b.bloggername}:${b.postdate}:${b.title}`)}return seen.size}
function isArtMuseum(x){return /미술관/i.test(`${x.name||''} ${x.category||''}`)}
function isPublicOrMajorMuseum(x){const t=`${x.name||''} ${x.category||''} ${x.place_url||''}`;return /국립|시립|도립|구립|군립|공립|광역시.*미술관|특별시.*미술관|리움|호암미술관|아모레퍼시픽미술관|뮤지엄\s*산|부산현대미술관|서울시립미술관|광주시립미술관|대구미술관|대전시립미술관|전남도립미술관|경남도립미술관|제주도립미술관/i.test(t)}
async function childReview365(x){const name=clean(x.name||x.display_name);if(!name)return 0;const terms=['아이','아기','어린이','유아','가족'];const min=dateNumDaysAgo(365),key=name.replace(/\s+/g,'').toLowerCase(),seen=new Set;for(const term of terms){const items=await nblog(`${name} ${locOf(x)} ${term}`,30);for(const b of items){if(+(b.postdate||0)<min)continue;const text=clean(`${b.title||''} ${b.description||''}`).replace(/\s+/g,'').toLowerCase();if(!text.includes(key)||!/아이와|아이랑|아이와함께|아기랑|아기와|어린이|유아|가족|자녀|아이들/.test(text))continue;seen.add(b.link||b.bloggerlink||`${b.bloggername}:${b.postdate}:${b.title}`)}}return seen.size}
async function museumGate(a){const out=[];for(const x of a||[]){if(!isArtMuseum(x)||isPublicOrMajorMuseum(x)){out.push(x);continue}const n=await childReview365(x);if(n>0)out.push({...x,child_blog_365d_count:n});}return out}
async function rankBlogs(a){const rows=await Promise.all((a||[]).map(async(x,i)=>({...x,blog_7d_count:await blog7(x),_i:i})));rows.sort((a,b)=>(b.blog_7d_count-a.blog_7d_count)||((+a.route_minutes||9999)-(+b.route_minutes||9999))||(a._i-b._i));return rows.map(({_i,...x})=>x)}
async function call(req,u,t){const v=new URL(u.toString());v.searchParams.set('themes',t==='water'?'season':t);const c=cap();await(await base())({...req,url:v.pathname+'?'+v.searchParams.toString(),query:{...(req.query||{}),themes:v.searchParams.get('themes')}},c);const o=c.out();let j;try{j=JSON.parse(o.b||'{}')}catch{return{j:null,o}}return{j,o}}
module.exports=async(req,res)=>{try{const u=new URL(req.url,'http://x'),ts=(u.searchParams.get('themes')||'').split(',').filter(Boolean);if(!ts.length)return(await base())(req,res);const rs=await Promise.all(ts.map(t=>call(req,u,t))),bad=rs.find(r=>!r.j||!r.j.ok);if(bad){res.statusCode=bad?.o?.c||500;return res.end(bad?.o?.b||JSON.stringify({ok:false,error:'추천 정보를 불러오지 못했습니다.'}))}let all=[];for(let i=0;i<rs.length;i++){const t=ts[i];let a=rs[i].j.items||[];if(t==='water')a=water(a,u.searchParams.get('visitDate'));else if(t==='season')a=a.filter(x=>x.festival||x.season_kind==='festival');else if(t==='craft')a=craft(a);else if(t==='experience')a=await museumGate(exp(a));else if(t==='playground')a=playground(a);all.push(...a.map(x=>({...x,matched_themes:[...new Set([...(x.matched_themes||[]).filter(k=>k!=='season'||t==='season'),t])]})))}all=await rankBlogs(dedupe(all));res.statusCode=200;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify({ok:true,transitEnabled:false,items:all,hasMore:rs.some(r=>r.j.hasMore)}))}catch(e){console.error(e);res.statusCode=500;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify({ok:false,error:e.message||String(e)}))}};
